export const tarrifInputField = {
  rental: [
    { value: "Local", text: "Local" },
    { value: "Slab Rate", text: "Slab Rate" },
    { value: "Out Station", text: "Out Station" },
    { value: "Airport Transfer", text: "Airport Transfer" },
    { value: "Hotel Transfer", text: "Hotel Transfer" },
    { value: "Flat Rate", text: "Flat Rate" },
    { value: "Trip rate", text: "Trip rate" },
    { value: "Shift Rate", text: "Shift Rate" },
    { value: "Day Rate", text: "Day Rate" },
    { value: "Escort Airport Transfer", text: "Escort Airport Transfer" },
    { value: "One Way", text: "One Way" },
    { value: "Two Way", text: "Two Way" },
    { value: "Railway Bus Transfer", text: "Railway Bus Transfer" },
    { value: "KMS Rate", text: "KMS Rate" },
  ],
  companies: [
    {
      value: "ANZ MTP",
      text: "ANZ MTP",
    },
    { value: "GE-JFWTC", text: "IBGE-JFWTCM" },
    { value: "GE", text: "GE" },
    { value: "IBM EGL", text: "IBM EGL" },
    { value: "IBM MTP", text: "IBM MTP" },
    {
      value: "IBS Software Private Limited",
      text: "IBS Software Private Limited",
    },
  ],
  vehicleTypes: [
    { value: "DZIRE", text: "DZIRE" },
    { value: "TT", text: "TT" },
    { value: "ERTIGA", text: "ERTIGA" },
    { value: "CRYSTA", text: "CRYSTA" },
    { value: "ETIOS", text: "ETIOS" },
    { value: "INNOVA", text: "INNOVA" },
  ],
  selectedRental: "Local",
  segment: [
    { value: "a/c", text: "a/c" },
    { value: "non a/s", text: "non a/c" },
  ],
  selectedSegment: "",
  area: [
    { value: "Hebbal", text: "Hebbal" },
    { value: "Tin Factory", text: "Tin Factory" },
    { value: "NarayanaPura", text: "NarayanaPura" },
  ],
  selectedArea: "",
  slabhrs: [
    { value: 1, text: "1 Hours" },
    { value: 2, text: "2 Hours" },
    { value: 3, text: "3 Hours" },
    { value: 4, text: "4 Hours" },
    { value: 5, text: "5 Hours" },
    { value: 6, text: "6 Hours" },
    { value: 8, text: "8 Hours" },
  ],
  selectedSlabhrs: "",
  slabkms: [
    { value: 10, text: "10 Kms" },
    { value: 20, text: "20 Kms" },
    { value: 30, text: "30 Kms" },
    { value: 40, text: "40 Kms" },
    { value: 50, text: "50 Kms" },
    { value: 80, text: "80 Kms" },
    { value: 300, text: "300 Kms" },
  ],
  selectedSlabkms: "",
  slabfrom: [
    { value: 1, text: 1 },
    { value: 2, text: 2 },
    { value: 3, text: 4 },
  ],
  selectedSlabfrom: "",
  slabto: [
    { value: 50, text: 50 },
    { value: 60, text: 60 },
    { value: 70, text: 70 },
  ],
  selectedSlabto: "",
  addon: [
    { value: "single", text: "Single" },
    { value: "escort", text: "Escort" },
  ],
  selectedAddon: "",
  salesRate: null,
  purchaseRate: null,
  salesExKmsRate: null,
  salesExHrsRate: null,
  purchaseExHrsRate: null,
  purchaseExKmsRate: null,
  purchaseGraceTime: null,
  salesGraceTime: null,
  driverbata: null,
  position: 1,
};
export const onCallMisrequiredFields = [
  "Usage_Date",
  "Vehicle_No",
  "Vehicle_Type",
  "Vehicle_Billed_As",
  "Segment",
  "Rental",
  "Company_Name",
];
export const tarrifExcelUploadrequiredFields = [
  "S.no",
  "Company Name",
  "Vehicle Type",
  "Rental",
  "Segment",
];
export const slabExcelUploadrequiredFields = [
  "Duty Type",
  "Company",
  "Trip ID",
  "Vehicle Billed as",
  "Segment",
];
