export const tarrifInputField = {
  rental: [
    { value: "local", text: "Local" },
    { value: "slab_rate", text: "Slab Rate" },
    { value: "out_station", text: "Out Station" },
    { value: "airport_transfer", text: "Airport Transfer" },
    { value: "hotel_transfer", text: "Hotel Transfer" },
    { value: "flat_rate", text: "Flat Rate" },
    { value: "trip_rate", text: "Trip rate" },
    { value: "shift_rate", text: "Shift Rate" },
    { value: "day_rate", text: "Day Rate" },
    { value: "escort_airport_transfer", text: "Escort Airport Transfer" },
    { value: "one_way", text: "One Way" },
    { value: "two_way", text: "Two Way" },
    { value: "railway_bus_transfer", text: "Railway Bus Transfer" },
    { value: "KMS_rate", text: "KMS Rate" },
  ],
  companies: [
    {
      value: "ANZ MTP",
      text: "ANZ MTP",
    },
    { value: "GE-JFWTC", text: "IBGE-JFWTCM" },
    { value: "GE", text: "GE" },
    { value: "IBM EGL", text: "IBM EGL" },
    { value: "IBM MTP", text: "IBM MTP" },
  ],
  vehicleTypes: [
    { value: "DZIRE", text: "DZIRE" },
    { value: "TT", text: "TT" },
    { value: "ERTIGA", text: "ERTIGA" },
    { value: "CRYSTA", text: "CRYSTA" },
    { value: "ETIOS", text: "ETIOS" },
    { value: "INNOVA", text: "INNOVA" },
  ],
  selectedRental: "local",
  segment: [
    { value: "ac", text: "Ac" },
    { value: "nonac", text: "Non/Ac" },
  ],
  selectedSegment: "",
  area: [
    { value: "Hebbal", text: "Hebbal" },
    { value: "Tin Factory", text: "Tin Factory" },
    { value: "NarayanaPura", text: "NarayanaPura" },
  ],
  selectedArea: "",
  slabhrs: [
    { value: 1, text: "1 Hours" },
    { value: 2, text: "2 Hours" },
    { value: 3, text: "3 Hours" },
    { value: 4, text: "4 Hours" },
    { value: 5, text: "5 Hours" },
    { value: 6, text: "6 Hours" },
    { value: 8, text: "8 Hours" },
  ],
  selectedSlabhrs: "",
  slabkms: [
    { value: 10, text: "10Kms" },
    { value: 20, text: "20Kms" },
    { value: 30, text: "30Kms" },
    { value: 40, text: "40Kms" },
    { value: 50, text: "50Kms" },
    { value: 80, text: "80Kms" },
    { value: 300, text: "80Kms" },
  ],
  selectedSlabkms: "",
  slabfrom: [
    { value: 1, text: 1 },
    { value: 2, text: 2 },
    { value: 3, text: 4 },
  ],
  selectedSlabfrom: "",
  slabto: [
    { value: 50, text: 50 },
    { value: 60, text: 60 },
    { value: 70, text: 70 },
  ],
  selectedSlabto: "",
  addon: [
    { value: "single", text: "Single" },
    { value: "escort", text: "Escort" },
  ],
  selectedAddon: "",
  salesRate: null,
  selectedSalesRate: "",
  purchaseRate: null,
  selectedPurchaseRate: "",
  salesExKmsRate: null,
  selectedSalesExKmsRate: "",
  salesExHrsRate: null,
  selectedSalesExHrsRate: "",
  purchaseExHrsRate: null,
  selectedPurchaseExHrsRate: "",
  purchaseExKmsRate: null,
  selectedPurchaseExKmsRate: "",
  purchaseGraceTime: null,
  selectedPurchaseGraceTime: "",
  salesGraceTime: null,
  selectedSalesGraceTime: "",
  driverbata: null,
  selectedDriverbata: "",
  position: 1,
};
